<a href="https://colab.research.google.com/github/Anudeepkonka/airline-ticket-automation/blob/main/Airline_Ticket_Automation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install spacy scikit-learn pandas nltk streamlit pyngrok joblib
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.14)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Collecting streamlit
  Downloading streamlit-1.58.0-py3-none-any.whl.metadata (9.6 kB)
Collecting pyngrok
  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (1.5.3)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.25.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.50)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.22.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.18)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.5.20)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.1)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.5.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.2.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Downloading streamlit-1.58.0-py3-none-any.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 51.1 MB/s eta 0:00:00
Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 105.7 MB/s eta 0:00:00
Installing collected packages: pyngrok, pydeck, streamlit
Successfully installed pydeck-0.9.2 pyngrok-8.1.2 streamlit-1.58.0
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 92.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [1]:
import pandas as pd
import numpy as np
import random

# Sample cities and names
cities = ["Hyderabad", "Delhi", "Mumbai", "Chennai", "Bangalore", "Kolkata"]
names = ["John", "Rahul", "Priya", "Anita", "Arjun", "Sneha"]

emails = []
intents = []

# Book Flight
for _ in range(40):
    emails.append(
        f"Book a flight for {random.choice(names)} from {random.choice(cities)} to {random.choice(cities)} tomorrow."
    )
    intents.append("Book Flight")

# Cancel Flight
for _ in range(40):
    emails.append(
        f"Please cancel my booking ABC{random.randint(100,999)}."
    )
    intents.append("Cancel Flight")

# Reschedule Flight
for _ in range(40):
    emails.append(
        f"Reschedule my flight to next Monday."
    )
    intents.append("Reschedule Flight")

# General Inquiry
for _ in range(40):
    emails.append(
        "What is the baggage allowance?"
    )
    intents.append("General Inquiry")

# Create DataFrame
df = pd.DataFrame({
    "email": emails,
    "intent": intents
})

# Shuffle data
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

# Save dataset
df.to_csv("airline_emails.csv", index=False)

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (160, 2)

                                  email             intent
0  Reschedule my flight to next Monday.  Reschedule Flight
1  Reschedule my flight to next Monday.  Reschedule Flight
2        What is the baggage allowance?    General Inquiry
3      Please cancel my booking ABC689.      Cancel Flight
4  Reschedule my flight to next Monday.  Reschedule Flight

In [2]:
# Basic EDA
print("Dataset Shape:", df.shape)

print("\nIntent Distribution:")
print(df['intent'].value_counts())

print("\nMissing Values:")
print(df.isnull().sum())

df.head()

Dataset Shape: (160, 2)

Intent Distribution:
intent
Reschedule Flight    40
General Inquiry      40
Cancel Flight        40
Book Flight          40
Name: count, dtype: int64

Missing Values:
email     0
intent    0
dtype: int64

                                  email             intent
0  Reschedule my flight to next Monday.  Reschedule Flight
1  Reschedule my flight to next Monday.  Reschedule Flight
2        What is the baggage allowance?    General Inquiry
3      Please cancel my booking ABC689.      Cancel Flight
4  Reschedule my flight to next Monday.  Reschedule Flight

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import joblib

# Features and target
X = df['email']
y = df['intent']

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# TF-IDF
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

# Train Logistic Regression
model = LogisticRegression(max_iter=1000)
model.fit(X_train_tfidf, y_train)

# Predictions
y_pred = model.predict(X_test_tfidf)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 1.0

Classification Report:
                   precision    recall  f1-score   support

      Book Flight       1.00      1.00      1.00         8
    Cancel Flight       1.00      1.00      1.00         8
  General Inquiry       1.00      1.00      1.00         8
Reschedule Flight       1.00      1.00      1.00         8

         accuracy                           1.00        32
        macro avg       1.00      1.00      1.00        32
     weighted avg       1.00      1.00      1.00        32

In [4]:
joblib.dump(model, "intent_model.pkl")
joblib.dump(tfidf, "tfidf.pkl")

print("Models saved successfully!")

Models saved successfully!

In [5]:
import os

print(os.listdir())

['.config', 'intent_model.pkl', 'tfidf.pkl', 'airline_emails.csv', 'sample_data']

In [6]:
import spacy
import re

nlp = spacy.load("en_core_web_sm")

def extract_entities(text):
    doc = nlp(text)

    entities = {
        "name": None,
        "source": None,
        "destination": None,
        "travel_date": None
    }

    # Passenger Name
    for ent in doc.ents:
        if ent.label_ == "PERSON":
            entities["name"] = ent.text

        elif ent.label_ == "DATE":
            entities["travel_date"] = ent.text

    # Source and Destination
    match = re.search(r'from\s+(\w+)\s+to\s+(\w+)', text, re.IGNORECASE)

    if match:
        entities["source"] = match.group(1)
        entities["destination"] = match.group(2)

    return entities

In [7]:
sample = "Book a flight for John from Hyderabad to Delhi tomorrow."

print(extract_entities(sample))

{'name': 'John', 'source': 'Hyderabad', 'destination': 'Delhi', 'travel_date': 'tomorrow'}

In [8]:
import joblib

# Load saved models
model = joblib.load("intent_model.pkl")
tfidf = joblib.load("tfidf.pkl")

def analyze_email(text):
    # Intent Prediction
    text_vector = tfidf.transform([text])

    intent = model.predict(text_vector)[0]

    confidence = round(
        max(model.predict_proba(text_vector)[0]) * 100,
        2
    )

    # Entity Extraction
    entities = extract_entities(text)

    return {
        "intent": intent,
        "confidence": confidence,
        "entities": entities
    }

In [9]:
sample = "Book a flight for John from Hyderabad to Delhi tomorrow."

result = analyze_email(sample)

print(result)

{'intent': 'Book Flight', 'confidence': np.float64(86.11), 'entities': {'name': 'John', 'source': 'Hyderabad', 'destination': 'Delhi', 'travel_date': 'tomorrow'}}

In [10]:
import joblib

# Load saved models
model = joblib.load("intent_model.pkl")
tfidf = joblib.load("tfidf.pkl")

def analyze_email(text):
    # Intent Prediction
    text_vector = tfidf.transform([text])

    intent = model.predict(text_vector)[0]

    confidence = round(
        max(model.predict_proba(text_vector)[0]) * 100,
        2
    )

    # Entity Extraction
    entities = extract_entities(text)

    return {
        "intent": intent,
        "confidence": confidence,
        "entities": entities
    }

In [12]:
sample = "Book a flight for John from Hyderabad to Delhi tomorrow."

result = analyze_email(sample)

print(result)

{'intent': 'Book Flight', 'confidence': np.float64(86.11), 'entities': {'name': 'John', 'source': 'Hyderabad', 'destination': 'Delhi', 'travel_date': 'tomorrow'}}

In [13]:
from google.colab import files

files.download("intent_model.pkl")
files.download("tfidf.pkl")
files.download("airline_emails.csv")

In [14]:
%%writefile app.py

import streamlit as st
import joblib
import spacy
import re

# Load models
model = joblib.load("intent_model.pkl")
tfidf = joblib.load("tfidf.pkl")
nlp = spacy.load("en_core_web_sm")

def extract_entities(text):
    doc = nlp(text)

    entities = {
        "name": None,
        "source": None,
        "destination": None,
        "travel_date": None
    }

    for ent in doc.ents:
        if ent.label_ == "PERSON":
            entities["name"] = ent.text

        elif ent.label_ == "DATE":
            entities["travel_date"] = ent.text

    match = re.search(r'from\\s+(\\w+)\\s+to\\s+(\\w+)', text, re.IGNORECASE)

    if match:
        entities["source"] = match.group(1)
        entities["destination"] = match.group(2)

    return entities

st.title("✈️ Airline Ticket Booking Automation System")

email = st.text_area("Paste Customer Email")

if st.button("Analyze"):

    if email.strip():

        vector = tfidf.transform([email])

        intent = model.predict(vector)[0]

        confidence = round(
            max(model.predict_proba(vector)[0]) * 100,
            2
        )

        entities = extract_entities(email)

        st.success("Analysis Complete")

        st.write("### Intent")
        st.write(intent)

        st.write("### Confidence")
        st.write(f"{confidence}%")

        st.write("### Extracted Details")
        st.json(entities)

    else:
        st.warning("Please enter an email.")

Writing app.py

In [15]:
%%writefile requirements.txt

streamlit
scikit-learn
spacy
pandas
numpy
joblib
nltk

Writing requirements.txt

In [16]:
files.download("app.py")
files.download("requirements.txt")